version: "3"

networks:
  default:
    external:
      name: cw_net

services:
  cw-php:
    container_name: cw-php
    build:
      context: ../php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../../dock-roboto/flow-business:/usr/share/apache2/htdocs/flow-business:cached
      - ../../dock-roboto/flow-business:/usr/local/apache2/htdocs/flow-business:cached
      #- ../../dock-roboto/flow-business/web:/usr/share/apache2/htdocs/flow-business/web/jamaica:cached
      #- ../../dock-roboto/flowbusiness_co:/usr/share/apache2/htdocs/flowbusiness_co:delegated
      - ../../dock-roboto/cwnetworks.com:/usr/share/apache2/htdocs/cwnetworks.com:delegated
      - ../../dock-roboto/cwbusiness.com:/usr/share/apache2/htdocs/cwbusiness.com:delegated
      #- ../../cwbusiness.com/core:/usr/share/apache2/htdocs/cwbusiness:delegated
      - ./logs:/var/log/php:delegated
